# Generated by Django 3.1.1 on 2020-09-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200929_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
